#!/bin/bash

if [ -z $1 ]
then
	name="default"
else
	name=$1
fi

template=$(find ~ -name favorite_preamble_ksimsek)
tex=$1/$1.tex
fig=$1/figures

mkdir $1
mkdir $fig

touch $tex
cat $template > $tex
if [ -z $(which texstudio) ]
then
	xdg-open $tex &
else
	texstudio $tex &
fi
